
import Foundation

enum PokedexData {
    static let kanto: [Pokemon] = [
        Pokemon(number: 1, name: "Bulbasaur", description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon."),
        Pokemon(number: 2, name: "Ivysaur", description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."),
        Pokemon(number: 3, name: "Venusaur", description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."),
        Pokemon(number: 4, name: "Charmander", description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."),
        Pokemon(number: 5, name: "Charmeleon", description: "When it swings its burning tail, it elevates the temperature to unbearably hot levels."),
        Pokemon(number: 6, name: "Charizard", description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally."),
        Pokemon(number: 7, name: "Squirtle", description: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth."),
        Pokemon(number: 8, name: "Wartortle", description: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."),
        Pokemon(number: 9, name: "Blastoise", description: "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles."),
        Pokemon(number: 10, name: "Caterpie", description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."),
        Pokemon(number: 11, name: "Metapod", description: "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body."),
        Pokemon(number: 12, name: "Butterfree", description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air."),
        Pokemon(number: 13, name: "Weedle", description: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head."),
        Pokemon(number: 14, name: "Kakuna", description: "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators."),
        Pokemon(number: 15, name: "Beedrill", description: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail."),
        Pokemon(number: 16, name: "Pidgey", description: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."),
        Pokemon(number: 17, name: "Pidgeotto", description: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder."),
        Pokemon(number: 18, name: "Pidgeot", description: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp."),
        Pokemon(number: 19, name: "Rattata", description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places."),
        Pokemon(number: 20, name: "Raticate", description: "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off."),
        Pokemon(number: 21, name: "Spearow", description: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne."),
        Pokemon(number: 22, name: "Fearow", description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest."),
        Pokemon(number: 23, name: "Ekans", description: "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole."),
        Pokemon(number: 24, name: "Arbok", description: "It is rumored that the ferocious warning markings on its belly differ from area to area."),
        Pokemon(number: 25, name: "Pikachu", description: "When several of these Pokémon gather, their electricity could build and cause lightning storms."),
        Pokemon(number: 26, name: "Raichu", description: "Its long tail serves as a ground to protect itself from its own high voltage power."),
        Pokemon(number: 27, name: "Sandshrew", description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food."),
        Pokemon(number: 28, name: "Sandslash", description: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."),
        Pokemon(number: 29, name: "Nidoran♀", description: "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns."),
        Pokemon(number: 30, name: "Nidorina", description: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting."),
        Pokemon(number: 31, name: "Nidoqueen", description: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves."),
        Pokemon(number: 32, name: "Nidoran♂", description: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."),
        Pokemon(number: 33, name: "Nidorino", description: "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom."),
        Pokemon(number: 34, name: "Nidoking", description: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones."),
        Pokemon(number: 35, name: "Clefairy", description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas."),
        Pokemon(number: 36, name: "Clefable", description: "A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people."),
        Pokemon(number: 37, name: "Vulpix", description: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older."),
        Pokemon(number: 38, name: "Ninetales", description: "Very smart and vengeful. Grabbing one of its many tails could result in a 1000-year curse."),
        Pokemon(number: 39, name: "Jigglypuff", description: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."),
        Pokemon(number: 40, name: "Wigglytuff", description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size."),
        Pokemon(number: 41, name: "Zubat", description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."),
        Pokemon(number: 42, name: "Golbat", description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly."),
        Pokemon(number: 43, name: "Oddish", description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds."),
        Pokemon(number: 44, name: "Gloom", description: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey."),
        Pokemon(number: 45, name: "Vileplume", description: "The larger its petals, the more toxic pollen it contains. It has the largest petals in the world."),
        Pokemon(number: 46, name: "Paras", description: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host."),
        Pokemon(number: 47, name: "Parasect", description: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places."),
        Pokemon(number: 48, name: "Venonat", description: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."),
        Pokemon(number: 49, name: "Venomoth", description: "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has."),
        Pokemon(number: 50, name: "Diglett", description: "Lives about one yard underground where it feeds on plant roots. It also appears above ground."),
        Pokemon(number: 51, name: "Dugtrio", description: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground."),
        Pokemon(number: 52, name: "Meowth", description: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change."),
        Pokemon(number: 53, name: "Persian", description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."),
        Pokemon(number: 54, name: "Psyduck", description: "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers."),
        Pokemon(number: 55, name: "Golduck", description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."),
        Pokemon(number: 56, name: "Mankey", description: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant."),
        Pokemon(number: 57, name: "Primeape", description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught."),
        Pokemon(number: 58, name: "Growlithe", description: "Very protective of its territory. It will bark and bite to repel intruders from its space."),
        Pokemon(number: 59, name: "Arcanine", description: "A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings."),
        Pokemon(number: 60, name: "Poliwag", description: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."),
        Pokemon(number: 61, name: "Poliwhirl", description: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy."),
        Pokemon(number: 62, name: "Poliwrath", description: "An expert swimmer that hunts for fish Pokémon. It can swim in the ocean without needing to breathe."),
        Pokemon(number: 63, name: "Abra", description: "Using its ability to read minds, it will identify impending danger and teleport to safety."),
        Pokemon(number: 64, name: "Kadabra", description: "It emits special alpha waves from its body that induce headaches just by being close by."),
        Pokemon(number: 65, name: "Alakazam", description: "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000."),
        Pokemon(number: 66, name: "Machop", description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger."),
        Pokemon(number: 67, name: "Machoke", description: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions."),
        Pokemon(number: 68, name: "Machamp", description: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon."),
        Pokemon(number: 69, name: "Bellsprout", description: "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture."),
        Pokemon(number: 70, name: "Weepinbell", description: "It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid."),
        Pokemon(number: 71, name: "Victreebel", description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there."),
        Pokemon(number: 72, name: "Tentacool", description: "Drifts in shallow seas. Anglers who hook them by accident are often punished by their stingers."),
        Pokemon(number: 73, name: "Tentacruel", description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey."),
        Pokemon(number: 74, name: "Geodude", description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."),
        Pokemon(number: 75, name: "Graveler", description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."),
        Pokemon(number: 76, name: "Golem", description: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."),
        Pokemon(number: 77, name: "Ponyta", description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time."),
        Pokemon(number: 78, name: "Rapidash", description: "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it."),
        Pokemon(number: 79, name: "Slowpoke", description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."),
        Pokemon(number: 80, name: "Slowbro", description: "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps."),
        Pokemon(number: 81, name: "Magnemite", description: "Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves."),
        Pokemon(number: 82, name: "Magneton", description: "Formed by several Magnemite linking together. They frequently appear when sunspots flare up."),
        Pokemon(number: 83, name: "Farfetch'd", description: "The sprig of green onions it holds is its weapon. It is used much like a metal sword."),
        Pokemon(number: 84, name: "Doduo", description: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints."),
        Pokemon(number: 85, name: "Dodrio", description: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake."),
        Pokemon(number: 86, name: "Seel", description: "The protruding horn on its head is very hard. It is used for bashing through thick ice."),
        Pokemon(number: 87, name: "Dewgong", description: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."),
        Pokemon(number: 88, name: "Grimer", description: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."),
        Pokemon(number: 89, name: "Muk", description: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."),
        Pokemon(number: 90, name: "Shellder", description: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."),
        Pokemon(number: 91, name: "Cloyster", description: "When attacked, it launches its horns in quick volleys. Its innards have never been seen."),
        Pokemon(number: 92, name: "Gastly", description: "Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice."),
        Pokemon(number: 93, name: "Haunter", description: "Because of its ability to slip through block walls, it is said to be from another dimension."),
        Pokemon(number: 94, name: "Gengar", description: "Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright."),
        Pokemon(number: 95, name: "Onix", description: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."),
        Pokemon(number: 96, name: "Drowzee", description: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."),
        Pokemon(number: 97, name: "Hypno", description: "When it locks eyes with an enemy, it will use a mix of psi powers such as Hypnosis and Confusion."),
        Pokemon(number: 98, name: "Krabby", description: "Its pincers are not only powerful, they are also very dexterous. It can catch prey by sea flowers."),
        Pokemon(number: 99, name: "Kingler", description: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use."),
        Pokemon(number: 100, name: "Voltorb", description: "Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people."),
        Pokemon(number: 101, name: "Electrode", description: "It stores electric energy under very high pressure. It often explodes with little or no provocation."),
        Pokemon(number: 102, name: "Exeggcute", description: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."),
        Pokemon(number: 103, name: "Exeggutor", description: "Legend has it that on rare occasions, one of its heads will drop off and continue living as an Exeggcute."),
        Pokemon(number: 104, name: "Cubone", description: "Because it never removes its skull helmet, no one has ever seen this Pokémon's real face."),
        Pokemon(number: 105, name: "Marowak", description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."),
        Pokemon(number: 106, name: "Hitmonlee", description: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."),
        Pokemon(number: 107, name: "Hitmonchan", description: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see."),
        Pokemon(number: 108, name: "Lickitung", description: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."),
        Pokemon(number: 109, name: "Koffing", description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."),
        Pokemon(number: 110, name: "Weezing", description: "Where two kinds of poison gases meet, 2 Koffing can fuse into a Weezing over many years."),
        Pokemon(number: 111, name: "Rhyhorn", description: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer truck flying."),
        Pokemon(number: 112, name: "Rhydon", description: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees."),
        Pokemon(number: 113, name: "Chansey", description: "A rare and elusive Pokémon that is said to bring happiness to those who manage to get it."),
        Pokemon(number: 114, name: "Tangela", description: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."),
        Pokemon(number: 115, name: "Kangaskhan", description: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old."),
        Pokemon(number: 116, name: "Horsea", description: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water."),
        Pokemon(number: 117, name: "Seadra", description: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."),
        Pokemon(number: 118, name: "Goldeen", description: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen."),
        Pokemon(number: 119, name: "Seaking", description: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."),
        Pokemon(number: 120, name: "Staryu", description: "An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle."),
        Pokemon(number: 121, name: "Starmie", description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem."),
        Pokemon(number: 122, name: "Mr. Mime", description: "If interrupted while it is miming, it will slap around the offender with its broad hands."),
        Pokemon(number: 123, name: "Scyther", description: "With ninja-like agility and speed, it can create the illusion that there is more than one."),
        Pokemon(number: 124, name: "Jynx", description: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."),
        Pokemon(number: 125, name: "Electabuzz", description: "Normally found near power plants, they can wander away and cause major blackouts in cities."),
        Pokemon(number: 126, name: "Magmar", description: "Its body always burns with an orange glow that enables it to hide perfectly among flames."),
        Pokemon(number: 127, name: "Pinsir", description: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard."),
        Pokemon(number: 128, name: "Tauros", description: "When it targets an enemy, it charges furiously while whipping its body with its long tails."),
        Pokemon(number: 129, name: "Magikarp", description: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."),
        Pokemon(number: 130, name: "Gyarados", description: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage."),
        Pokemon(number: 131, name: "Lapras", description: "A Pokémon that has been overhunted almost to extinction. It can ferry people across bodies of water."),
        Pokemon(number: 132, name: "Ditto", description: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy."),
        Pokemon(number: 133, name: "Eevee", description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones."),
        Pokemon(number: 134, name: "Vaporeon", description: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."),
        Pokemon(number: 135, name: "Jolteon", description: "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts."),
        Pokemon(number: 136, name: "Flareon", description: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees."),
        Pokemon(number: 137, name: "Porygon", description: "A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace."),
        Pokemon(number: 138, name: "Omanyte", description: "Although long extinct, in rare cases, it can be genetically resurrected from fossils."),
        Pokemon(number: 139, name: "Omastar", description: "A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey."),
        Pokemon(number: 140, name: "Kabuto", description: "A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago."),
        Pokemon(number: 141, name: "Kabutops", description: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids."),
        Pokemon(number: 142, name: "Aerodactyl", description: "A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like fangs."),
        Pokemon(number: 143, name: "Snorlax", description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."),
        Pokemon(number: 144, name: "Articuno", description: "A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains."),
        Pokemon(number: 145, name: "Zapdos", description: "A legendary bird Pokémon that's said to appear from clouds while dropping enormous lightning bolts."),
        Pokemon(number: 146, name: "Moltres", description: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames."),
        Pokemon(number: 147, name: "Dratini", description: "Long considered a mythical Pokémon until recently when a small colony was found living underwater."),
        Pokemon(number: 148, name: "Dragonair", description: "A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions."),
        Pokemon(number: 149, name: "Dragonite", description: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans."),
        Pokemon(number: 150, name: "Mewtwo", description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."),
        Pokemon(number: 151, name: "Mew", description: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."),
    ]
    static let johto: [Pokemon] = [
        Pokemon(number: 152, name: "Chikorita", description: "A sweet aroma gently wafts from the leaf on its head. It is docile and loves to soak up the sun's rays."),
        Pokemon(number: 153, name: "Bayleef", description: "The scent of spices comes from around its neck. Somehow, sniffing it makes you want to fight."),
        Pokemon(number: 154, name: "Meganium", description: "The aroma that rises from its petals contains a substance that calms aggressive feelings."),
        Pokemon(number: 155, name: "Cyndaquil", description: "It is timid, and always curls itself up in a ball. If attacked, it flares up its back for protection."),
        Pokemon(number: 156, name: "Quilava", description: "Be careful if it turns its back during battle. It means that it will attack with the fire on its back."),
        Pokemon(number: 157, name: "Typhlosion", description: "If its rage peaks, it becomes so hot that anything that touches it will instantly go up in flames."),
        Pokemon(number: 158, name: "Totodile", description: "Its well-developed jaws are powerful and capable of crushing almost anything. Even its trainer must be careful."),
        Pokemon(number: 159, name: "Croconaw", description: "If it loses a fang, a new one grows back in its place. There are always 48 fangs lining its mouth."),
        Pokemon(number: 160, name: "Feraligatr", description: "When it bites with its massive and powerful jaws, it shakes its head and savagely tears its victim up."),
        Pokemon(number: 161, name: "Sentret", description: "A very cautious Pokémon, it raises itself up using its tail to get a better view of its surroundings."),
        Pokemon(number: 162, name: "Furret", description: "It makes a nest to suit its long and thin body. The nest is impossible for other Pokémon to enter."),
        Pokemon(number: 163, name: "Hoothoot", description: "It always stands on one foot. It changes feet so fast, the movement can rarely be seen."),
        Pokemon(number: 164, name: "Noctowl", description: "Its eyes are specially adapted. They concentrate even faint light and enable it to see in the dark."),
        Pokemon(number: 165, name: "Ledyba", description: "It is very timid. It will be afraid to move if it is alone. But it will be active if it is in a group."),
        Pokemon(number: 166, name: "Ledian", description: "When the stars flicker in the night sky, it flutters about, scattering a glowing powder."),
        Pokemon(number: 167, name: "Spinarak", description: "It lies still in the same pose for days in its web, waiting for its unsuspecting prey to wander close."),
        Pokemon(number: 168, name: "Ariados", description: "It spins string not only from its rear but also from its mouth. It is hard to tell which end is which."),
        Pokemon(number: 169, name: "Crobat", description: "The development of wings on its legs enables it to fly fast but also makes it tough to stop and rest."),
        Pokemon(number: 170, name: "Chinchou", description: "It shoots positive and negative electricity between the tips of its two antennae and zaps its enemies."),
        Pokemon(number: 171, name: "Lanturn", description: "The light it emits is so bright that it can illuminate the sea's surface from a depth of over three miles."),
        Pokemon(number: 172, name: "Pichu", description: "It is not yet skilled at storing electricity. It may send out a jolt if amused or startled."),
        Pokemon(number: 173, name: "Cleffa", description: "Because of its unusual, star-like silhouette, people believe that it came here on a meteor."),
        Pokemon(number: 174, name: "Igglybuff", description: "It has a soft and bouncy body. Once it starts bouncing, it becomes impossible to stop."),
        Pokemon(number: 175, name: "Togepi", description: "The shell seems to be filled with joy. It is said that it will share good luck when treated kindly."),
        Pokemon(number: 176, name: "Togetic", description: "They say that it will appear before kindhearted, caring people and shower them with happiness."),
        Pokemon(number: 177, name: "Natu", description: "Because its wings aren't yet fully grown, it has to hop to get around. It is always staring at something."),
        Pokemon(number: 178, name: "Xatu", description: "They say that it stays still and quiet because it is seeing both the past and future at the same time."),
        Pokemon(number: 179, name: "Mareep", description: "If static electricity builds in its body, its fleece doubles in volume. Touching it will shock you."),
        Pokemon(number: 180, name: "Flaaffy", description: "As a result of storing too much electricity, it developed patches where even downy wool won't grow."),
        Pokemon(number: 181, name: "Ampharos", description: "The tail's tip shines so brightly that it can be used to send messages to far-off shores."),
        Pokemon(number: 182, name: "Bellossom", description: "When Bellossom gets exposed to plenty of sunlight, the leaves around its body begin to spin around."),
        Pokemon(number: 183, name: "Marill", description: "The tip of its tail, which contains oil that is lighter than water, lets it swim without drowning."),
        Pokemon(number: 184, name: "Azumarill", description: "By keeping still and listening intently, it can tell what is in even wild, fast-moving rivers."),
        Pokemon(number: 185, name: "Sudowoodo", description: "Although it always pretends to be a tree, its composition appears to be closer to a rock than a plant."),
        Pokemon(number: 186, name: "Politoed", description: "The curled hair on Politoed's head is proof of its status as a king. It is said that the longer and more curled the hair, the more respect this Pokémon earns from its peers."),
        Pokemon(number: 187, name: "Hoppip", description: "This Pokémon drifts and floats with the wind. If it senses the approach of strong winds, Hoppip links its leaves with other Hoppip to prepare against being blown away."),
        Pokemon(number: 188, name: "Skiploom", description: "The bloom on top of its head opens and closes as the temperature fluctuates up and down."),
        Pokemon(number: 189, name: "Jumpluff", description: "Once it catches the wind, it deftly controls its cotton-puff spores to float, even around the world."),
        Pokemon(number: 190, name: "Aipom", description: "Its tail is so powerful that it can use it to grab a tree branch and hold itself up in the air."),
        Pokemon(number: 191, name: "Sunkern", description: "It may drop out of the sky suddenly. If attacked by a Spearow, it will violently shake its leaves."),
        Pokemon(number: 192, name: "Sunflora", description: "It converts sunlight into energy. In the darkness after sunset, it closes its petals and becomes still."),
        Pokemon(number: 193, name: "Yanma", description: "If it flaps its wings really fast, it can generate shock waves that will shatter windows in the area."),
        Pokemon(number: 194, name: "Wooper", description: "This Pokémon lives in cold water. It will leave the water to search for food when it gets cold outside."),
        Pokemon(number: 195, name: "Quagsire", description: "This carefree Pokémon has an easy-going nature. While swimming, it always bumps into boat hulls."),
        Pokemon(number: 196, name: "Espeon", description: "It uses the fine hair that covers its body to sense air currents and predict its enemy's actions."),
        Pokemon(number: 197, name: "Umbreon", description: "When agitated, this Pokémon protects itself by spraying poisonous sweat from its pores."),
        Pokemon(number: 198, name: "Murkrow", description: "Feared and loathed by many, it is believed to bring misfortune to all those who see it at night."),
        Pokemon(number: 199, name: "Slowking", description: "Every time it yawns, Shellder injects more poison into it. The poison makes it more intelligent."),
        Pokemon(number: 200, name: "Misdreavus", description: "It likes to lurk in the dark and tap shoulders with a gaseous hand. Its touch causes endless shuddering."),
        Pokemon(number: 201, name: "Unown", description: "Their shapes look like hieroglyphs on ancient tablets. It is said that the two are somehow related."),
        Pokemon(number: 202, name: "Wobbuffet", description: "It hates light and shock. If attacked, it inflates its body to pump up its counterstrike."),
        Pokemon(number: 203, name: "Girafarig", description: "Its tail has a small brain of its own. Beware! If you get close, it may react to your scent and bite."),
        Pokemon(number: 204, name: "Pineco", description: "It likes to make its shell thicker by adding layers of tree bark. The additional weight doesn't bother it."),
        Pokemon(number: 205, name: "Forretress", description: "Its entire body is shielded by a steel-hard shell. What lurks inside this shell is a total mystery."),
        Pokemon(number: 206, name: "Dunsparce", description: "When spotted, this Pokémon escapes backward by furiously boring into the ground with its tail."),
        Pokemon(number: 207, name: "Gligar", description: "It flies straight at its target's face then clamps down on the startled victim to inject poison."),
        Pokemon(number: 208, name: "Steelix", description: "Its body has been compressed deep under the ground. As a result, it is even harder than a diamond."),
        Pokemon(number: 209, name: "Snubbull", description: "Although it looks frightening, it is actually kind and affectionate. It is very popular among women."),
        Pokemon(number: 210, name: "Granbull", description: "It is actually timid and easily spooked. If attacked, it flails about to fend off its attacker."),
        Pokemon(number: 211, name: "Qwilfish", description: "To fire its poison spikes, it must inflate its body by drinking over 2.6 gallons of water all at once."),
        Pokemon(number: 212, name: "Scizor", description: "It swings its eye-patterned pincers up to scare its foes. This makes it look like it has three heads."),
        Pokemon(number: 213, name: "Shuckle", description: "The berries stored in its vaselike shell decompose and become a gooey liquid."),
        Pokemon(number: 214, name: "Heracross", description: "This powerful Pokémon thrusts its prized horn under its enemies' bellies then lifts and throws them."),
        Pokemon(number: 215, name: "Sneasel", description: "Its paws conceal sharp claws. If attacked, it suddenly extends the claws and startles its enemy."),
        Pokemon(number: 216, name: "Teddiursa", description: "If it finds honey, its crescent mark glows. It always licks its paws because they are soaked with honey."),
        Pokemon(number: 217, name: "Ursaring", description: "Although it is a good climber, it prefers to snap trees with its forelegs and eat fallen berries."),
        Pokemon(number: 218, name: "Slugma", description: "It never sleeps. It has to keep moving because if it stopped, its magma body would cool and harden."),
        Pokemon(number: 219, name: "Magcargo", description: "The shell on its back is just skin that has cooled and hardened. It breaks easily with a slight touch."),
        Pokemon(number: 220, name: "Swinub", description: "It rubs its snout on the ground to find and dig up food. It sometimes discovers hot springs."),
        Pokemon(number: 221, name: "Piloswine", description: "Because the long hair all over its body obscures its sight, it just keeps charging repeatedly."),
        Pokemon(number: 222, name: "Corsola", description: "In a south sea, there is a coral reef where the branches are colored in pink. It is Corsola's reef."),
        Pokemon(number: 223, name: "Remoraid", description: "It has superb accuracy. The water it shoots out can strike moving prey from more than 300 feet."),
        Pokemon(number: 224, name: "Octillery", description: "It traps enemies with its suction-cupped tentacles then smashes them with its rock-hard head."),
        Pokemon(number: 225, name: "Delibird", description: "It carries food all day long. There are tales about lost people who were saved by the food it had."),
        Pokemon(number: 226, name: "Mantine", description: "As it majestically swims, it doesn't care if Remoraid attach to it for scavenging its leftovers."),
        Pokemon(number: 227, name: "Skarmory", description: "After nesting in bramble bushes, the wings of its chicks grow hard from scratches by thorns."),
        Pokemon(number: 228, name: "Houndour", description: "It uses different kinds of cries for communicating with others of its kind and for pursuing its prey."),
        Pokemon(number: 229, name: "Houndoom", description: "If you are burned by the flames it shoots from its mouth, the pain will never go away."),
        Pokemon(number: 230, name: "Kingdra", description: "It is said that it usually hides in underwater caves. It can create whirlpools by yawning."),
        Pokemon(number: 231, name: "Phanpy", description: "For its nest, Phanpy digs a vertical pit in the ground at the edge of a river. It marks the area around its nest with its trunk."),
        Pokemon(number: 232, name: "Donphan", description: "It attacks by curling up then rolling into its foe. It can blow apart even the hardest rocks."),
        Pokemon(number: 233, name: "Porygon2", description: "This upgraded version of Porygon is designed for space exploration. It can't fly, though."),
        Pokemon(number: 234, name: "Stantler", description: "Its antlers bend and change shape in subtle ways. Those who glimpse them are said to lose their way."),
        Pokemon(number: 235, name: "Smeargle", description: "A special fluid oozes from the tip of its tail. It paints the fluid everywhere to mark its territory."),
        Pokemon(number: 236, name: "Tyrogue", description: "It is always bursting with energy. To make itself stronger, it keeps on fighting even if it loses."),
        Pokemon(number: 237, name: "Hitmontop", description: "If you become enchanted by its smooth, elegant, dance-like kicks, you may get drilled hard."),
        Pokemon(number: 238, name: "Smoochum", description: "It actively runs about, but also falls often. Whenever it falls, it will check its reflection on a lake's surface."),
        Pokemon(number: 239, name: "Elekid", description: "It rotates its arms to generate electricity, but it tires easily, so it charges up only a little bit."),
        Pokemon(number: 240, name: "Magby", description: "Each and every time it inhales and exhales, hot embers dribble out of its mouth and nostrils."),
        Pokemon(number: 241, name: "Miltank", description: "Its milk is packed with nutrition, making it the ultimate beverage for the sick or weary."),
        Pokemon(number: 242, name: "Blissey", description: "Anyone who takes even one bite of Blissey's egg becomes unfailingly caring and pleasant to everyone."),
        Pokemon(number: 243, name: "Raikou", description: "The rain clouds it carries let it fire thunderbolts at will. They say that it descended with lightning."),
        Pokemon(number: 244, name: "Entei", description: "Volcanoes erupt when it barks. Unable to restrain its extreme power, it races headlong around the land."),
        Pokemon(number: 245, name: "Suicune", description: "Said to be the reincarnation of north winds, it can instantly purify filthy, murky water."),
        Pokemon(number: 246, name: "Larvitar", description: "Born deep underground, it comes aboveground and becomes a pupa once it has finished eating the surrounding soil."),
        Pokemon(number: 247, name: "Pupitar", description: "Its body is as hard as bedrock. By venting pressurized gas, it can launch itself like a rocket."),
        Pokemon(number: 248, name: "Tyranitar", description: "Its body can't be harmed by any sort of attack, so it is very eager to make challenges against enemies."),
        Pokemon(number: 249, name: "Lugia", description: "It is said to be the guardian of the seas. It is rumored to have been seen on the night of a storm."),
        Pokemon(number: 250, name: "Ho-Oh", description: "Its feathers are in seven colors. It is said that anyone seeing it is promised eternal happiness."),
        Pokemon(number: 251, name: "Celebi", description: "This Pokémon came from the future by crossing over time. It is thought that so long as Celebi appears, a bright and shining future awaits us."),
    ]

    
}
